name = "SweepContractor"
uuid = "75a5deae-e917-4509-af32-a989148c8d5f"
authors = ["Christopher Chubb <github@christopherchubb.com>"]
version = "0.1.6"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.4"
DataStructures = "0.18.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
