name = "SweepContractor"
uuid = "75a5deae-e917-4509-af32-a989148c8d5f"
authors = ["Christopher Chubb <github@christopherchubb.com>"]
version = "0.1.4"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.4"
